library(QDNAseq)
library(DNAcopy)
library(BSgenome.Hsapiens.UCSC.hg19)
# bins <- getBinAnnotations(binSize=220, genome="hg19")
bins <- createBins(BSgenome.Hsapiens.UCSC.hg19, 220)
saveRDS(bins,file = "bin_annotations_220Kbp.rds")
