library(QDNAseq)
library(DNAcopy)
# bins <- getBinAnnotations(binSize=100, genome="hg19")
# saveRDS(bins,file = "bin_annotations_100kbp.rds")
# bins <- readRDS("bin_annotations_10kbp.rds")

files <- list.files(path="/home/garner1/Work/dataset/reduced_sequencing/bamfiles", pattern="\\.bam$", full.names=T, recursive=FALSE)

bins <- readRDS("bin_annotations_100kbp.rds")
for (x in files){
  readCounts <- binReadCounts(bins,bamfiles=x)  
  readCountsFiltered <- applyFilters(readCounts,residual=TRUE, blacklist=TRUE)
  readCountsFiltered <- estimateCorrection(readCountsFiltered)
  copyNumbers <- correctBins(readCountsFiltered)
  copyNumbersNormalized <- normalizeBins(copyNumbers)
  copyNumbersSmooth <- smoothOutlierBins(copyNumbersNormalized)
  copyNumbersSegmented <- segmentBins(copyNumbersSmooth, transformFun="sqrt",smoothBy = 1L)
  copyNumbersSegmented <- normalizeSegmentedBins(copyNumbersSegmented)
  copyNumbersCalled <- callBins(copyNumbersSegmented,method = "cutoff")
  filename<- paste(x, ".pdf", sep="")
  pdf(filename)
  plot(copyNumbersCalled)  
  dev.off()
  filename <- paste(x,".bed", sep="")
  exportBins(copyNumbersSegmented, filename, format = "bed")  
  # exportBins(copyNumbersCalled, format="vcf")
  filename <- paste(x,".tsv",sep="")
  exportBins(copyNumbersCalled, filename, type = "segments", format="tsv")
}

  ######################################################
bamfile='/home/garner1/LANShareDownloads/XZ108BICRO100.CATCACGC.deduplicated.bam'
bins <- readRDS("/home/garner1/Dropbox/pipelines/CNV/bin_annotations_5kbp.rds")
readCounts <- binReadCounts(bins,bamfiles=bamfile)  
readCountsFiltered <- applyFilters(readCounts,residual=TRUE, blacklist=TRUE)
readCountsFiltered <- estimateCorrection(readCountsFiltered)
copyNumbers <- correctBins(readCountsFiltered)
copyNumbersNormalized <- normalizeBins(copyNumbers)
copyNumbersSmooth <- smoothOutlierBins(copyNumbersNormalized)
copyNumbersSegmented <- segmentBins(copyNumbersSmooth, transformFun="sqrt",smoothBy = 1L)
copyNumbersSegmented <- normalizeSegmentedBins(copyNumbersSegmented)
filename <- paste(bamfile,".bed", sep="")
exportBins(copyNumbersSegmented, filename, format = "bed")  
